export const BILLING_SUMMARY_FETCHED = 'BILLING_SUMMARY_FETCHED'
export const TAB_SELECTED = 'TAB_SELECTED'
export const TAB_SHOWED = 'TAB_SHOWED'
export const BILLING_CYCLES_FETCHED = 'BILLING_CYCLES_FETCHED'

export const TOKEN_VALIDATED = 'TOKEN_VALIDATED'
export const USER_FETCHED = 'USER_FETCHED'